theme: jekyll-theme-dinky
logo: https://avatars0.githubusercontent.com/u/46445292
title: preferans-deck-js
description: preferans deck of cards
show_downloads: "true"
include:
  - "_*_.html"
  - "_*_.*.html"